### ISSUE TITLE
Fix GSoC data extractor

### ISSUE THREAD

**Issue by Pro-Panda** [Pro-Panda/utility-scripts#8]
Following things need to be fixed:
 - Add doc strings and clean the code
 - Look for json files being used when the website is loaded(Inspect Element > Network)
 - There are two types of websites: archive(containing 2017 and before), current (2018) They use different type of requests and provide different types of data
 - All the past years data should come into one excel file. So that I can see number of projects accepted by an org from year to year. Also, there is a skill set column for 2016 and 2017. also extract that and make that as a column

Names of the orgs changed slightly from year to year in terms of lower case etc. This will make multiple rows for one org. To fix this:
 - Use the re module to remove any special characters from the org names.
 - Make all org names lower case

@cheese-cracker, look into this

**Comment by cheese-cracker** [comment]
1> Will do 
2> Pending- Will try to get, have got their urls
3> Pending
4> I haven't been able to merge common orgs..  so I made one json file = 1 sheet in excel doc
5/6> Will do those as well
I'll try to do it by tom ..got a little distracted lately!

**Comment by Pro-Panda** [comment]
4. Common orgs must be merged, only then is it easy to track their past performaces

**Comment by Pro-Panda** [comment]
Fixed
